/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DigitalLife3D (https://sketchfab.com/DigitalLife3D)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/model-72b-juvenile-green-sea-turtle-c90a930f8b2a4cc8bc516742a0df01d9
title: Model 72B - Juvenile Green Sea Turtle
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
          <group name="green_016_round5changes_johnsonfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="green_juvenilearmature" position={[-2.27, 2.99, -2.19]} rotation={[-Math.PI / 2, 0, -3.12]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_39" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_42" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.greeneye} skeleton={nodes.Object_40.skeleton} />
                    <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.greeneyeouter} skeleton={nodes.Object_41.skeleton} />
                    <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.greenbody} skeleton={nodes.Object_43.skeleton} />
                  </group>
                </group>
                <group name="green_juvenileeye" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="green_juvenilemesh" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
