/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DigitalLife3D (https://sketchfab.com/DigitalLife3D)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/model-50a-hawksbill-sea-turtle-e69458ef8176402d919df421e444da86
title: Model 50A - Hawksbill Sea Turtle
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.18}>
          <group name="Root">
            <group name="Hawksbillarmature">
              <group name="Hawksbillmesh" position={[-0.01, 0.05, 0]} />
              <primitive object={nodes.Hawksbillarmature_rootJoint} />
              <skinnedMesh name="Hawksbillmesh_0" geometry={nodes.Hawksbillmesh_0.geometry} material={materials['hawksbill.body']} skeleton={nodes.Hawksbillmesh_0.skeleton} />
              <skinnedMesh name="Hawksbillmesh_1" geometry={nodes.Hawksbillmesh_1.geometry} material={materials.outer} skeleton={nodes.Hawksbillmesh_1.skeleton} />
              <skinnedMesh name="Hawksbillmesh_2" geometry={nodes.Hawksbillmesh_2.geometry} material={materials['hawksbill.eyes']} skeleton={nodes.Hawksbillmesh_2.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
